-- Task 21: bilingual exhibition labels for the frozen Second Batch Volume I (D2-01..D2-30).
-- Summaries preserve the catalog's cultural reading while keeping authentication claims separate.

CREATE TEMP TABLE d2_labels(
  catalog_code TEXT,
  zh_label TEXT,
  zh_text TEXT,
  eo_label TEXT,
  eo_text TEXT
) ON COMMIT DROP;

INSERT INTO d2_labels VALUES
('D2-01','天鸡高鸣：晨启与觉醒','器物以禽鸟形制、金属骨架与彩色装饰构成。展陈以“晨启、报晓、由静入明”为文化意象；“元代、铜雕、掐丝珐琅彩”等沿用收藏登记名，年代与工艺仍待专业核定。','La Ĉiela Koko: matena vekiĝo','La objekto havas birdan formon kun metala strukturo kaj koloraj ornamaĵoj. La ekspozicio uzas la bildon de matena vekiĝo kaj transiro de silento al lumo. Datigo kaj tekniko en la titolo restas kolektaj terminoj ĝis faka kontrolo.'),
('D2-02','随身修持的绿度母造像','小型佛像式器物以深绿色釉感和金色细节为主要视觉特征。展陈强调“把愿带在身边”及修行进入日常；“五代、柴窑”等为收藏登记名，待专业鉴定。','Portebla bildo de Verda Tārā','La malgranda budhisma figuro montras profundverdan glazuran aspekton kaj orkolorajn detalojn. La ekspozicia temo estas porti la aspiron en la ĉiutagan vivon. La historia kaj forna atribuo restas registra nomo ĝis faka identigo.'),
('D2-03','寿星与有质量的长寿','青黄相间的人物雕呈传统寿星形象。展陈从“长寿”延伸到长者经验、记忆与智慧的保存；材质、年代等依现有登记保存并待鉴定。','Longviveco kaj digna maljuniĝo','La figuro montras tradician bildon de longviveco kun bluverdaj kaj flavaj tonoj. La ekspozicio etendas la temon al digno, memoro kaj saĝo en maljunaĝo; materialo kaj dato restas submetitaj al kontrolo.'),
('D2-04','暖黄寿星：安住与传承','暖黄至金黄色人物雕形成温厚、安稳的长者形象。展陈强调“老有所安、老有所传”；登记名称与材质、年代不替代专业鉴定。','Varma longviveca figuro: sekureco kaj heredo','La varmaj flavaj tonoj kaj trankvila figuro prezentas mildan dignon. La ekspozicio ligas longvivecon kun sekura maljuniĝo kaj transdono de sperto; la registra titolo ne anstataŭas fakan identigon.'),
('D2-05','网络失而复得的石样档案','本件以强金属光泽和多变色泽进入收藏与网络传播记忆。其价值之一在旧图像散失后重新被检索、归档的数字考古过程；“锎陨石”等仅为历史收藏称谓，不作为成分或天体来源结论。','Cifereca retrovo de perdita specimen-arkivo','La specimeno estas memorata pro forta metala brilo kaj ŝanĝiĝantaj koloroj. Grava parto de la dosiero estas la retrovo de perditaj retaj bildoj. La historia kolekta nomo ne estas kemia aŭ astronomia konkludo.'),
('D2-06','金龟印玺与文明记忆','器物以龟形与印玺结构结合，兼具吉祥意象与文人故事联想。展陈可借“留下印记”表达文明记忆与传承；人物关联与年代需由独立文献和器物研究核验。','Ora testudo-sigelo kaj civiliza memoro','La objekto kunigas testudan formon kun sigela strukturo kaj kulturaj rakontoj. La ekspozicio emfazas la ideon lasi spuron por memoro kaj heredo; historiaj atribuoj bezonas apartan dokumentan kaj objektan kontrolon.'),
('D2-07','蛋形石样：星种与孕育','红褐至深红的蛋形石样具有颗粒感与局部亮点。展陈以“种子、星体、孕育”为视觉联想；“碳质、微纳米钻石、陨石”等仍是收藏登记术语，待检测。','Ovoforma specimeno: stelsemo kaj naskiĝo','La ovoforma brunruĝa specimeno havas grajnecan surfacon kaj lokajn brilojn. La ekspozicio uzas la bildojn de semo, astro kaj naskiĝo; la materialaj kaj meteoraj terminoj restas kolektaj ĝis analizo.'),
('D2-08','未知、探索与命名','深色基体上可见金属样亮点及复杂颗粒结构。展陈强调面对陌生自然物“先观察、再命名、再学习”；名称中的天体、元素与钻石属性待科学检测。','Nekonato, esploro kaj nomado','La malhela specimeno montras metalajn brilpunktojn kaj kompleksan grajnecan strukturon. La ekspozicio emfazas observi antaŭ nomi kaj lerni antaŭ konkludi; astronomiaj kaj materialaj atributoj bezonas sciencan analizon.'),
('D2-09','微观中见宏观','深色石体具有细颗粒、晶亮点与不规则表面。展陈以“一点微光成为观察宇宙物质的入口”为主题；名称中的高碳、微纳米钻石、陨石等属性待检测。','Vidi la grandan en la eta','La malhela specimeno havas densajn grajnojn, kristalajn brilojn kaj neregulan surfacon. La ekspozicio vidas en eta brilo enirejon al scivolemo pri materia universo; la teknikaj terminoj en la titolo restas por kontrolo.'),
('D2-10','貔貅：从护财到守护共同财富','兽形器物以青灰、深绿色调与卷云式纹饰形成守护兽意象。展陈把传统“守护”扩展到知识、文化、记忆与公益；年代和材质仍按收藏登记名保留。','Pixiu: gardi komunan riĉecon','La bestforma objekto kun bluverdaj tonoj kaj nubaj ornamaĵoj prezentas protektan bildon. La ekspozicio vastigas la ideon de gardado al scio, kulturo, memoro kaj publika bono; dato kaj materialo restas registraj ĝis kontrolo.'),
('D2-11','天青双兽：守护之后见晴明','一对天青至蓝青釉兽形器左右呼应。展陈将成双守护与“雨过天晴”的清明意境结合；“五代、柴窑”等为收藏登记名，文化记忆与同期文献需区分。','Ĉielbluaj paraj bestoj: klareco post gardado','La paro de blu-glazuraj bestformaj objektoj respondas unu al la alia. La ekspozicio kunligas protekton kun klareco post pluvo; la dinastia kaj forna atribuo restas registra titolo kaj ne samtempula pruvo.'),
('D2-12','透明不是空无','无色透明至近无色石样内部可见颗粒、包体与强折射。展陈以“透明并非空无，而是容纳、折射与显现”为主题；材质与天体来源待检测。','Travideblo ne estas nenio','La senkolora travidebla specimeno enhavas grajnojn, inkluzivaĵojn kaj fortan refrakton. La ekspozicio montras travideblon kiel enhavon, refrakton kaj aperon; materialo kaj deveno restas esplorendaj.'),
('D2-13','石中桃花源','天然纹理形成类似山体、云气与远近层次的画面感。展陈与凤凰文明“桃花源”愿景呼应：先在自然纹理中看见理想空间，再思考共同生活；材质待鉴定。','Taohuayuan en ŝtono','Naturaj vejnoj sugestas montojn, nubojn kaj pejzaĝajn tavolojn. La ekspozicio ligas la objekton al la vizio de Taohuayuan: unue vidi idealan pejzaĝon en naturo, poste pripensi komunan vivon; materialo restas por kontrolo.'),
('D2-14','海与天之间的凝望','深海蓝至钴蓝色石样在不同角度下呈透明、半透明与多层反光。展陈以天空与深海两个“无边”意象表现人类面对未知的凝望；“玻璃陨石”等属性待检测。','Rigardo inter maro kaj ĉielo','La marblua ĝis kobaltoblua specimeno montras travideblajn tavolojn kaj ŝanĝiĝantajn reflektojn. La ekspozicio kunligas la senlimecon de ĉielo kaj oceano kiel homan rigardon al nekonato; la registra materiala titolo bezonas analizon.'),
('D2-15','笛声与语言之桥','蜜黄至黄褐色人物立像持横笛于胸前。展陈以“声音虽不可见，却能跨越空间”连接音乐与世界语的沟通使命；“古黄玉、唐人”等为收藏标题，待鉴定。','Flutsono kaj lingva ponto','La mielflava figuro tenas transversan fluton ĉe la brusto. La ekspozicio ligas la nevideblan vojaĝon de sono kun la komunikada rolo de Esperanto; la historia kaj materiala titolo restas kolekta ĝis identigo.'),
('D2-16','粗粝中的微光','浅灰多孔、颗粒状基体中散布深色颗粒与金黄色亮点。展陈以“价值不一定只在光滑表面”为主题；贵金属、黄金、钻石、陨石等称谓需检测确认。','Eta lumo en krudeco','En hela pora kaj grajneca bazo aperas malhelaj grajnoj kaj orkoloraj brilpunktoj. La ekspozicio emfazas ke valoro ne ĉiam kuŝas sur glata surfaco; metalaj, diamantaj kaj meteoraj terminoj bezonas analizon.'),
('D2-17','象形大熊猫与观看关系','深灰黑至褐黑色石样因轮廓与天然凹凸产生类似熊猫或兽形的象形联想。展陈强调意义由自然形态与人的观看共同生成；“无球璃”等按原登记保留，待后续核定。','Zoomorfa pando kaj la ago de rigardado','La malhela specimeno sugestas pandon aŭ bestan formon pro sia natura konturo kaj reliefo. La ekspozicio montras ke signifo naskiĝas inter natura formo kaj homa percepto; neklaraj registraj terminoj restas ĝis posta kontrolo.'),
('D2-18','红色生命力与鹤文化','鲜红至橙红色透明至半透明石样具有流纹、包体与强烈色彩层次。“鹤顶红”在此作为色彩与文化命名，展陈联系飞翔、长寿与生命力；不据此推定材质或来源。','Ruĝa viveco kaj grua kulturo','La brile ruĝa ĝis oranĝruĝa specimeno montras fluoliniojn, inkluzivaĵojn kaj fortajn kolorajn tavolojn. La nomo estas traktata kiel kolora kaj kultura bildo ligita al flugo kaj longviveco, ne kiel materiala aŭ devena konkludo.'),
('D2-19','心形与天然舞纹','红白相间的心形抛光饰品中，天然纹理形成类似人物与舞姿的象形画面。展陈重点在“人如何从自然中发现故事”；材质、年代与工艺按登记保存并待核定。','Korformo kaj natura dancbildo','En la ruĝ-blanka korforma polurita objekto naturaj vejnoj sugestas homan figuron kaj dancon. La ekspozicio demandas kiel homoj trovas rakontojn en naturo; materialo, dato kaj tekniko restas registraj ĝis kontrolo.'),
('D2-20','鹦鹉、声音与沟通','浅色透明至半透明石样在不同光线下显多色反光，局部轮廓被观看为鹦鹉。展陈把鹦鹉与语言、模仿、传声相连，象征从复述走向理解；材质和来源待检测。','Papago, sono kaj komunikado','La hela travidebla specimeno montras plurkolorajn reflektojn kaj konturon perceptatan kiel papago. La ekspozicio ligas ĝin al lingvo, imitado kaj la vojo de ripeto al kompreno; materialo kaj deveno restas por analizo.'),
('D2-21','看不见的作用力','银灰至深灰的金属样石体具有不规则块状结构，“带磁性”作为收藏观察记录保存。展陈以磁性象征肉眼不可见却能产生连接的作用力；元素与天体来源待检测。','Nevidebla forto','La arĝentgriza ĝis malhelgriza specimeno havas metalan aspekton kaj neregulan strukturon; magneteco estas konservata kiel observa noto. La ekspozicio uzas magnetismon kiel bildon de nevidebla ligo; elementa kaj astrala deveno bezonas analizon.'),
('D2-22','鱼形奇石与生命流动','黄褐至米白色抛光石体的天然环带和斑纹产生鱼形联想。展陈借“有水则游、有路则行”表达适应、自由与生命循环；材质与年代待核定。','Fiŝforma kurioza ŝtono kaj vivfluo','Naturaj ringoj kaj makuloj en la flava-bruna ĝis kremblanka polurita ŝtono sugestas fiŝon. La ekspozicio uzas la bildon de naĝado por adaptiĝo, libereco kaj vivciklo; materialo kaj dato restas por kontrolo.'),
('D2-23','人机共生的未来提问','深黑、金属光泽的细长主体与不规则附着部分产生“人体与机械结合”的象形联想。展陈不试图证明“外星人”，而是提出未来人机共生、技术责任与主体性问题；天体和材质属性待检测。','Demando pri estonta homo-maŝina kunvivado','La malhela metale brila formo kun neregulaj aldonaĵoj sugestas hom-maŝinan figuron. La ekspozicio ne provas pruvi eksterteran originon, sed demandas pri kunvivado kun teknologio, respondeco kaj homa agkapablo; materialaj kaj astralaj atributoj restas por analizo.'),
('D2-24','虹光与多元并存','石样表面呈蓝绿、紫红、虹彩与金属样光泽，视频还记录了接近磁体样物的观察过程。展陈以“同一表面因角度不同而显不同颜色”象征多语言、多文化共同观看；名称属性待检测。','Irizeco kaj kunekzisto de diverseco','La specimeno montras bluverdajn, violruĝajn, irizajn kaj metalajn reflektojn, kaj la video registras magnet-similan observon. La ekspozicio uzas ŝanĝiĝantajn kolorojn kiel bildon de multlingva kaj multkultura rigardado; la teknikaj nomoj restas por kontrolo.'),
('D2-25','观察先于结论','深灰褐色石体密布片状、晶簇状反光颗粒，转动时出现银灰、棕金及彩色亮点。展陈强调先记录所见，再讨论名称与成分；标题中的“解”等字样按原登记保留，待确认。','Observado antaŭ konkludo','La profundgrizbruna specimeno havas multajn lamenajn kaj kristal-amasajn reflektajn grajnojn. La ekspozicio emfazas registri tion, kion oni vidas, antaŭ ol diskuti nomon kaj konsiston; neklaraj registraj vortoj restas ĝis konfirmo.'),
('D2-26','荒凉想象中的生命颜色','绿色至灰绿色粗糙石体夹有浅色矿脉与斑块。展陈把绿色生命意象与“月球”收藏名的荒寂想象并置；“预石”等按原输入保留，具体材质与天体来源待检测。','Koloro de vivo en dezerta imago','La verda ĝis grizverda kruda specimeno havas helajn vejnojn kaj makulojn. La ekspozicio kontraŭmetas verdan vivsimbolon al la dezerta imago de la kolekta nomo “Luno”; la neklaraj terminaj kaj devenaj asertoj restas por analizo.'),
('D2-27','热烈之后的安定','深枣红至酒红色透明至半透明石样在透光下显现内部层次与柔和反射。展陈把枣红理解为成熟、沉淀与愿力经过时间后的稳固；材质与来源待检测。','Trankvilo post intenseco','La profunda jujubruĝa ĝis vinruĝa travidebla specimeno montras internajn tavolojn kaj mildajn reflektojn. La ekspozicio interpretas la koloron kiel maturecon, sedimenton kaj stabilan aspiron post tempo; materialo kaj deveno restas por analizo.'),
('D2-28','为何总想走得更远','深灰黑至黑褐色不规则石样表面粗糙、多孔，呈干燥荒原般的地貌感。“火星”作为收藏名用于承载人类向外探索的想象，展陈不据此证明来源。','Kial homoj ĉiam volas iri pli for?','La malhelgriza ĝis nigrebruna neregula specimeno havas krudan poran surfacon kaj dezertan pejzaĝan impreson. “Marso” estas traktata kiel kolekta nomo por homa esplor-imago, ne kiel pruvo de deveno.'),
('D2-29','裂隙中的时间','红褐至砖红色石样具有黑色裂隙、脉纹与金属样斑点。展陈把每一道裂隙理解为长期变化留下的痕迹，并联系文明在裂隙、修复与继续中形成；“尹丁石”等按原登记保留。','Tempo en fendoj','La ruĝbruna ĝis brikruĝa specimeno havas nigrajn fendojn, vejnojn kaj metalajn makulojn. La ekspozicio vidas en ĉiu fendo spuron de longa ŝanĝo kaj ligas ĝin al civilizo formiĝanta per rompoj, riparoj kaj daŭrigo; la registra nomo estas konservata.'),
('D2-30','愿从光起，行以生命完成','金黄、橙红与枣红色层次交叠，内部可见色带、流纹与包体，转动时形成火焰般的视觉流动。作为第一册第30件，展陈以金色象征光与愿、红色象征生命与行动；材质与来源仍待检测。','La aspiro naskiĝas el lumo kaj plenumiĝas per vivo','Orflavaj, oranĝruĝaj kaj jujubruĝaj tavoloj kun fluolinioj kaj inkluzivaĵoj kreas flaman movon. Kiel la trideka objekto de la volumo, la ekspozicio uzas oron por lumo kaj aspiro, ruĝon por vivo kaj agado; materialo kaj deveno restas por analizo.');

INSERT INTO asset_exhibition_texts(asset_id,locale,short_label,exhibition_text,status,version)
SELECT a.id,'zh',l.zh_label,l.zh_text,'published','d2-v0.1'
FROM d2_labels l JOIN cultural_assets a ON a.catalog_code=l.catalog_code
ON CONFLICT(asset_id,locale,version) DO NOTHING;

INSERT INTO asset_exhibition_texts(asset_id,locale,short_label,exhibition_text,status,version)
SELECT a.id,'eo',l.eo_label,l.eo_text,'published','d2-v0.1'
FROM d2_labels l JOIN cultural_assets a ON a.catalog_code=l.catalog_code
ON CONFLICT(asset_id,locale,version) DO NOTHING;
