-- Task 22: bilingual exhibition labels for the frozen Third Volume (30 records).
-- Visible features are separated from collector naming and scientific/authentication conclusions.

CREATE TEMP TABLE v3_labels(
  catalog_code TEXT,
  zh_label TEXT,
  zh_text TEXT,
  eo_label TEXT,
  eo_text TEXT
) ON COMMIT DROP;

INSERT INTO v3_labels VALUES
('第三册-01','手中佛头：形制与修学空间','视频可见青蓝色手持佛头，螺发清楚，面部完整，颈部或底部中空。“五代、柴窑、青釉”为藏家暂定名，年代、窑口与材质仍待专业鉴定。','Budha kapo en la mano: formo kaj praktika spaco','La video montras bluverdan porteblan Budhan kapon kun klare videblaj harbukloj, kompleta vizaĝo kaj kava kolo aŭ bazo. La terminoj pri epoko, forno kaj glazuro estas provizoraj kolektaj nomoj ĝis faka identigo.'),
('第三册-02','蛋形石样：月球命名与检测边界','视频显示深灰黑色蛋形或卵石状物，表面圆润并有浅白斑点或包体。“月球陨石”为藏家暂定名，需矿物学、元素及同位素等检测后方可判断来源。','Ovoforma specimeno: luna nomo kaj analiza limo','La video montras malhelgrizan ĝis nigran ovoforman specimenon kun rondigita surfaco kaj helaj makuloj aŭ inkluzivaĵoj. “Luna meteorito” estas provizora kolekta nomo; deveno bezonas mineralogian, elementan kaj izotopan analizon.'),
('第三册-03','黑色晶粒与强反光石样','视频可见深灰至银灰块状物，强反光，密集晶粒或片状闪光，局部似透明或半透明。“灵神星、纳米黑钻、陨石”等属性待检测。','Malhela kristala specimeno kun forta reflektado','La video montras malhelgrizan ĝis arĝentgrizan blokon kun forta reflektado kaj densaj kristal- aŭ lamen-similaj briloj. La terminoj “Lingŝen-stelo”, “nano-nigra diamanto” kaj “meteorito” restas por analiza kontrolo.'),
('第三册-04','磁性展示与颗粒金属光泽','视频可见浅灰白不规则块体，局部有大量银白或金属样颗粒，并记录测试物接触。“磁性”为展示记录；“贵金属、锎、陨石”等属性待检测。','Magneta observado kaj metaleca grajneco','La video montras helgrizan neregulan specimenon kun multaj arĝentblankaj aŭ metalecaj grajnoj kaj kontakta provo per testobjekto. Magneteco estas registra observado; valormetala, kalifornia kaj meteorita identigo bezonas analizon.'),
('第三册-05','层状金属光泽石样','视频可见银灰至灰黑楔形或块状物，强反光并有层状、条带状纹理。“灵神星、贵金属、锎、陨石”为藏家登记名，待科学检测。','Tavoligita metaleca specimeno','La video montras arĝentgrizan ĝis malhelgrizan kojno- aŭ blokforman specimenon kun forta reflektado kaj tavolaj strioj. La astronomiaj kaj materialaj terminoj en la titolo estas kolektaj ĝis scienca analizo.'),
('第三册-06','火星如意金箍棒：形象命名','视频显示细长棒状、深红褐至黑褐色石质物，表面起伏粗糙并有局部金属样反光。“火星”来源待检测，“如意金箍棒”为形象命名。','Marsa Ruyi-bastono: figura nomado','La video montras longan baston-similan malhelruĝbrunan ĝis nigrebrunan ŝtonan objekton kun kruda surfaco kaj lokaj metalecaj briloj. “Marso” bezonas devenan analizon, dum “Ruyi-bastono” estas figura kolekta nomo.'),
('第三册-07','红褐木雕《马到成功》','视频可见大型红褐色木雕，含马匹、人物及卷曲构件，局部见青绿色装饰痕迹。“红土沉香”材质与产地为藏家暂定名，待香材鉴定。','Ruĝbruna ligna skulptaĵo “Sukceso kun alveno de la ĉevalo”','La video montras grandan ruĝbrunan lignan skulptaĵon kun ĉevaloj, homaj figuroj kaj kurbaj elementoj, parte kun bluverdaj ornamaĵspuroj. La materiala nomo “ruĝtera agar-ligno” estas provizora ĝis ligna kaj aroma identigo.'),
('第三册-08','青灰釉花觚与开片','视频可见青灰至青绿色釉瓷花器，器身与内壁有开片，外壁见凸起白色花鸟竹枝纹。“元代、仿官釉、套白玫”等称谓待陶瓷专业鉴定。','Bluverda glazura florujo kun krakela reto','La video montras bluverdan glazuritan porcelanan florujo kun krakela reto interne kaj ekstere kaj reliefaj blankaj flor-, bird- kaj bambuornamaĵoj. La dinastia kaj glazur-teknika atribuo restas por faka ceramika identigo.'),
('第三册-09','红色石样与浅色脉纹','视频显示红至红褐色不规则块体，贯穿白或灰白脉状、带状纹理，局部见深灰黑点。“火星、伊丁红、陨石”等属性待检测。','Ruĝa specimeno kun helaj vejnoj','La video montras ruĝan ĝis ruĝbrunan neregulan specimenon kun blankaj aŭ grizblankaj vejnoj kaj lokaj malhelaj punktoj. La terminoj “Marso”, “Yiding-ruĝo” kaj “meteorito” restas por analiza kontrolo.'),
('第三册-10','青黄人物镂空雕','视频可见青黄至黄绿色半透明人物雕，女性长衣飘带，见花饰、衣纹与镂空处理。“古代、青玉”为藏家暂定名，年代与材质待鉴定。','Bluverda-flava penetrita virina skulptaĵo','La video montras duontravideblan bluverdan ĝis flavverdan virinan figuron kun longa robo, rubandoj, floraj detaloj kaj penetrita laboro. La terminoj “antikva” kaj “bluverda jado” estas kolektaj ĝis faka kontrolo.'),
('第三册-11','彩绘人物将军罐','视频显示带盖大罐，白地与粉红锦地区结合，开光内有人物故事、花卉与器物多彩纹饰。“清代、珐琅彩、《西厢记》纹”为藏家暂定名，年代、彩料与题材待鉴定。','Kolore pentrita general-vazo kun figuraj scenoj','La video montras grandan kovrilan vazon kun blanka kaj rozkolora fono, figuraj scenoj, floroj kaj diversaj objektoj. La atribuo al Qing-epoko, emajla tekniko kaj la temo de “Okcidenta Ĉambro” restas por ceramika kaj ikonografia identigo.'),
('第三册-12','结核状深色石样','视频可见深褐至黑褐圆钝不规则块体，具有多个圆丘或结核状隆起与局部金属样光泽。外部比对图仅作形态参考，不作为命名或鉴定依据。','Malhela nodoza specimeno','La video montras profundbrunan ĝis nigrebrunan rondan neregulan specimenon kun pluraj nodaj elstaraĵoj kaj lokaj metalecaj briloj. Eksteraj komparbildoj servas nur por forma komparo kaj ne pruvas nomon aŭ identigon.'),
('第三册-13','多彩玻璃样石体','视频显示红褐、橙红、黄褐与灰色交织的多彩块体，局部透明或半透明，见玻璃样光泽与层带、流纹结构。“火星、宝石红、高晶玻璃陨石”待检测。','Plurkolora vitrec-aspekta specimeno','La video montras ruĝbrunajn, oranĝruĝajn, flavbrunajn kaj grizajn zonojn, parte travideblajn, kun vitrececa brilo kaj fluaj strioj. La terminoj pri Marsa deveno kaj materialo restas por analizo.'),
('第三册-14','磁性展示与粗晶闪光','视频可见灰黑至银灰强反光粗晶或片晶状块体，并记录测试件与标本接触、吸附的展示。“磁性”为视频观察记录；其余属性待检测。','Magneta observado kun krudkristala brilo','La video montras griznigran ĝis arĝentgrizan fortreflektan specimenon kun krudaj kristal- aŭ lamen-similaj surfacoj kaj kontakta testo. Magneteco estas observa registro; astronomia kaj diamanta identigo bezonas analizon.'),
('第三册-15','细长楔形金属样石体','视频显示细长扁片或楔形块体，一面黄褐—青灰并有细小亮点，另一面褐金—银灰颗粒与金属样闪光。“微磁”为展示记录，其余材质与来源待检测。','Longa kojnoforma metaleca specimeno','La video montras longan platan aŭ kojnoforman specimenon: unu flanko estas flavbruna-bluverda kun etaj briloj, la alia brunora-arĝentgriza kun metaleca grajneco. “Mikromagneta” estas observa noto; aliaj materialaj kaj devenaj terminoj bezonas analizon.'),
('第三册-16','海蓝透明大块体','视频可见鲜艳海蓝或蓝绿色透明至半透明大块体，强玻璃样光泽，并有贝壳状或不规则断口、裂隙与流纹。“月球、海蓝宝、玻璃陨石”待检测。','Marblua travidebla granda specimeno','La video montras vive marbluan aŭ bluverdan grandan travideblan ĝis duontravideblan specimenon kun forta vitrececa brilo, neregulaj rompoj, fendoj kaj fluaj linioj. La luna, akvamarina kaj meteorita atribuo bezonas analizon.'),
('第三册-17','扁平黑亮石样与微磁展示','视频显示灰黑至银黑扁平块体，密布强反光颗粒或片晶样结构，局部有浅棕、土黄色斑块。“微磁”为展示记录；“火星、纳米钻石、陨石”等待检测。','Plata nigre brila specimeno kun magneta observado','La video montras griznigran ĝis arĝentnigran platan specimenon kun densaj reflektaj grajnoj aŭ lamensimilaj strukturoj kaj helbrunaj makuloj. La magneta noto estas observa; Marsa, nano-diamanta kaj meteorita identigo restas por analizo.'),
('第三册-18','褐金与金属闪光石样','视频可见黄铜金至褐金不规则块体，密布细粒或片状金属样闪光，局部有紫褐斑带及浅灰半透明区域。“灵神星、微纳米、黄金钻、陨石”待检测。','Brunora specimeno kun metalecaj briloj','La video montras latunoran ĝis brunoran neregulan specimenon kun densaj metalecaj grajnoj aŭ lamenoj, violbrunaj zonoj kaj kelkaj helgrizaj duontravideblaj partoj. La teknikaj kaj astronomiaj terminoj restas por analizo.'),
('第三册-19','深色粗糙石体与晶点','视频显示深灰褐至黑褐块体，表面粗糙并密布细小亮点或晶点，局部呈红褐与青灰区域。“火星、纳米钻石、陨石”等属性待检测。','Malhela kruda specimeno kun kristalpunktoj','La video montras profundgrizbrunan ĝis nigrebrunan krudan specimenon kun multaj etaj bril- aŭ kristalpunktoj kaj lokaj ruĝbrunaj kaj bluverdaj zonoj. La Marsa, nano-diamanta kaj meteorita atribuo bezonas analizon.'),
('第三册-20','虹彩颗粒与放射性谨慎原则','视频显示灰褐至银灰不规则块体，细密颗粒与金属样反光明显，局部见蓝紫、紫红虹彩。网络截图只作参考，不能证明含锎或陨石身份；如怀疑放射性，应由有资质机构检测。','Irizaj grajnoj kaj principo de radiologia singardo','La video montras grizbrunan ĝis arĝentgrizan neregulan specimenon kun fajna grajneco, metalecaj reflektadoj kaj bluviolaj aŭ violruĝaj irizoj. Retaj bildoj ne pruvas kalifornion aŭ meteoritan identecon; ebla radioaktiveco devas esti kontrolata nur de kvalifikita institucio.'),
('第三册-21','蓝釉小罐与窑口待鉴','视频可见小型鼓腹罐，短颈圆口，蓝釉深浅变化，局部白色流釉或斑块，底部见支烧或露胎样点。“宋、钧”为藏家暂定名，年代与窑口待专业鉴定。','Malgranda blu-glazura vazo kun nekonfirmita forno','La video montras malgrandan ventroforman vazon kun mallonga kolo, ronda buŝo, ŝanĝiĝanta blua glazuro, blankaj fluaj makuloj kaj eblaj subtenaj brulspuroj ĉe la bazo. La Song- kaj Jun-atribuo restas provizora ĝis ceramika identigo.'),
('第三册-22','浅银灰颗粒石样','视频可见浅灰至银灰不规则小块体，局部密布银白或深色颗粒与金属样闪光。本件与第三册-12不是同一件；“灵神星、稀有贵金属、锎、陨石”待检测。','Hel-arĝentgriza grajneca specimeno','La video montras malgrandan helgrizan ĝis arĝentgrizan neregulan specimenon kun densaj arĝentblankaj aŭ malhelaj grajnoj kaj metalecaj briloj. Ĝi estas aparta de objekto 12; la astronomiaj kaj materialaj terminoj bezonas analizon.'),
('第三册-23','哮天犬象形与磁性展示','视频显示较大型扁厚不规则块体，灰褐至银黑，密集晶粒或片状金属样闪光，并记录测试件接触。“哮天犬”为形象命名，“微磁”为展示记录，其余属性待检测。','Zoomorfa “Xiaotian-hundo” kun magneta observado','La video montras pli grandan platan dikan neregulan specimenon, grizbrunan ĝis arĝentnigran, kun densaj kristal- aŭ lamen-similaj metalecaj briloj kaj kontakta testo. “Xiaotian-hundo” estas figura nomo; magneteco estas observa noto; aliaj atributoj bezonas analizon.'),
('第三册-24','黑色晶点石样与磁性记录','视频可见灰黑至黑褐不规则块体，表面粗糙，密布银白晶点样反光与片状金属光泽，并有测试件接触展示。“磁性”为藏家实测或展示记录，其余属性待检测。','Nigra kristalpunkta specimeno kun magneta registro','La video montras griznigran ĝis nigrebrunan krudan specimenon kun multaj arĝentblankaj kristalpunktaj kaj lamenaj metalecaj reflektadoj, kune kun kontakta testo. Magneteco estas kolektanta observa registro; aliaj atributoj bezonas analizon.'),
('第三册-25','翠绿色双柄鼻烟壶','视频显示深绿至翠绿色扁壶形小件，短颈扁圆腹，两侧耳或柄状凸起，见福字与卷云样纹饰并有一定透光感。“清、老坑、翡翠”为藏家暂定名，年代与材质待鉴定。','Verdkolora du-tenila tabakujo','La video montras malhelverdan ĝis smeraldverdan platan malgrandan botelon kun mallonga kolo, rondigita korpo, flankaj tenil-similaj elstaraĵoj, la signo “fu” kaj nubaj ornamaĵoj, kun iom da lumtransiro. La Qing-, “malnova minejo”- kaj jada atribuo restas por faka identigo.'),
('第三册-26','方孔钱样器物与钱文待释','视频可见圆形方孔铜钱样器物，深褐至黑褐，表面锈蚀或附着，正面四字钱文当前画面不足以可靠释读。“圣元通宝、古汉字、铜母钱”为藏家暂定名，需钱币专业鉴定。','Kvadrattrua monersimila objekto kun nelegita surskribo','La video montras rondan kvadrattruan kupro-mon-similan objekton, profundbrunan ĝis nigrebrunan, kun korodo kaj kvar-signa surskribo ne sufiĉe klara por fidinda legado. La titolo restas provizora ĝis numismatika identigo.'),
('第三册-27','流光纹带与金凤尾形象','既有视频可见黄褐、蜜黄、黑褐与灰绿色纹带交织，抛光面具有明显流动感。“金凤尾”为藏家形象命名，材质、年代与矿物学属性待鉴定。','Fluantaj vejnoj kaj la bildo de ora feniksa vosto','La video montras interplektitajn flavbrunajn, mielflavajn, nigrebrunajn kaj grizverdajn vejnojn sur polurita surfaco kun forta sento de fluo. “Ora feniksa vosto” estas figura kolekta nomo; materialo, dato kaj mineralogio restas por kontrolo.'),
('第三册-28','青花彩釉瓷碗与底款谨慎释读','视频可见碗内青花花卉、淡红彩与绿色茎叶，口沿褐红描边，外壁绿色叶纹，圈足底见青花双圈及四字款识。底款不凭模糊画面强释，“清中期、珐琅彩”为藏家暂定名，待陶瓷专业鉴定。','Blua-kaj-kolora porcelana bovlo kun singarda legado de la marko','La video montras internajn bluajn florojn kun palruĝaj kaj verdaj detaloj, brunruĝan randon, verdajn foliojn ekstere kaj kvar-signan bazmarkon ene de bluaj duoblaj ringoj. La neklara marko ne estas devige legata; la dinastia kaj emajla atribuo restas por ceramika identigo.'),
('第三册-29','已编入但待补独立影像核对','本件此前已确认名称并列入续编，现正式进入第三册。当前造册资料中尚缺独立外观细节核对，故只保留登记名称与待补证据状态，不扩写材质或来源结论。','Enregistrita sed ankoraŭ atendanta apartan bildan kontrolon','La objekto estis jam nomita kaj nun estas formale en la tria volumo, sed la nuna dosiero ankoraŭ mankas apartan detalan bildan kontrolon. Tial la registro konservas la nomon kaj la bezonon de plia pruvo sen pligrandigi materialajn aŭ devenajn konkludojn.'),
('第三册-30','凤眼菩提佛珠：法物与材质待核','本件此前已确认名称并列入续编，现正式进入第三册。现有登记按佛珠类别保存；独立外观细节、材质、年代与工艺仍待补图或实物资料核定。','Bodhi-rozario kun feniksokulaj semoj: ritobjekto kun materialo por kontrolo','La objekto estis jam registrita kaj nun formale eniras la trian volumon. Ĝi estas konservata kiel budhisma rozario laŭ la kolekta registro; apartaj bildaj detaloj, materialo, dato kaj metio ankoraŭ bezonas pliajn fotojn aŭ objektan dokumentadon.');

INSERT INTO asset_exhibition_texts(asset_id,locale,short_label,exhibition_text,status,version)
SELECT a.id,'zh',l.zh_label,l.zh_text,'published','v3-v0.1'
FROM v3_labels l JOIN cultural_assets a ON a.catalog_code=l.catalog_code
ON CONFLICT(asset_id,locale,version) DO NOTHING;

INSERT INTO asset_exhibition_texts(asset_id,locale,short_label,exhibition_text,status,version)
SELECT a.id,'eo',l.eo_label,l.eo_text,'published','v3-v0.1'
FROM v3_labels l JOIN cultural_assets a ON a.catalog_code=l.catalog_code
ON CONFLICT(asset_id,locale,version) DO NOTHING;
